### ISSUE TITLE
Questions page will not accept non-empty text

### ISSUE THREAD

**Issue by Blu12345** [JacksonChen666/JacksonChen666.github.io#13]
in the questions (https://jacksonchen666.com/questions) and ideas (https://jacksonchen666.com/ideas) section of the your website it tells you to try and type something no matter if you actually type anything or not and sends you to https://jacksonchen666.000webhostapp.com/Submit.php
reproduce by typing something in the ask or ideas text box and sending it works (or doesn't work I guess) on safari and chrome didn't test on opera

good luck

**Comment by JacksonChen666** [comment]
found the bug, didn't specify the textarea_name for the questions/ideas page when including the post_text.md file

**Comment by JacksonChen666** [comment]
just looked more into it, other properties other than the textarea_name gets properly inputted and textarea_name just refused to work

**Comment by Blu12345** [comment]
I read nothing

**Comment by JacksonChen666** [comment]
it looks like i made a rookie mistake, not putting the letter `q` in a string. pushing fix...
